/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simclavier;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author msoulard
 */
public class FenClavier extends javax.swing.JFrame {

    /**
     * Creates new form FenClavier
     */
    public FenClavier() {
        initComponents();
        jButton0.addActionListener(new GestionnaireTouche());
        jButton1.addActionListener(new GestionnaireTouche());
        jButton2.addActionListener(new GestionnaireTouche());
        jButton3.addActionListener(new GestionnaireTouche());
        jButton4.addActionListener(new GestionnaireTouche());
        jButton5.addActionListener(new GestionnaireTouche());
        jButton6.addActionListener(new GestionnaireTouche());
        jButton7.addActionListener(new GestionnaireTouche());
        jButton8.addActionListener(new GestionnaireTouche());
        jButton9.addActionListener(new GestionnaireTouche());
        jButtonDiese.addActionListener(new GestionnaireTouche());
        jButtonEtoile.addActionListener(new GestionnaireTouche());
    }
    private int compteurErreur = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        textMess = new javax.swing.JTextField();
        fondClavier = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonEtoile = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonDiese = new javax.swing.JButton();

        jButton10.setText("*");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clavier");
        setPreferredSize(new java.awt.Dimension(220, 250));
        setResizable(false);
        setSize(new java.awt.Dimension(220, 320));
        getContentPane().setLayout(null);

        textMess.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(textMess);
        textMess.setBounds(20, 20, 180, 40);

        fondClavier.setBackground(new java.awt.Color(153, 153, 255));
        fondClavier.setPreferredSize(new java.awt.Dimension(120, 160));
        fondClavier.setLayout(new java.awt.GridLayout(4, 3, 1, 1));

        jButton7.setText("7");
        jButton7.setToolTipText("Appuyer");
        jButton7.setMaximumSize(new java.awt.Dimension(26, 26));
        jButton7.setMinimumSize(new java.awt.Dimension(26, 26));
        jButton7.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton7);

        jButton8.setText("8");
        jButton8.setToolTipText("Appuyer");
        jButton8.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton8);

        jButton9.setText("9");
        jButton9.setToolTipText("Appuyer");
        jButton9.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton9);

        jButton4.setText("4");
        jButton4.setToolTipText("Appuyer");
        jButton4.setPreferredSize(new java.awt.Dimension(26, 26));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        fondClavier.add(jButton4);

        jButton5.setText("5");
        jButton5.setToolTipText("Appuyer");
        jButton5.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton5);

        jButton6.setText("6");
        jButton6.setToolTipText("Appuyer");
        jButton6.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton6);

        jButton1.setText("1");
        jButton1.setToolTipText("Appuyer");
        jButton1.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton1);

        jButton2.setText("2");
        jButton2.setToolTipText("Appuyer");
        jButton2.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton2);

        jButton3.setText("3");
        jButton3.setToolTipText("Appuyer");
        jButton3.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton3);

        jButtonEtoile.setText("*");
        jButtonEtoile.setToolTipText("Appuyer");
        jButtonEtoile.setPreferredSize(new java.awt.Dimension(26, 26));
        jButtonEtoile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEtoileMouseClicked(evt);
            }
        });
        fondClavier.add(jButtonEtoile);

        jButton0.setText("0");
        jButton0.setToolTipText("Appuyer");
        jButton0.setPreferredSize(new java.awt.Dimension(26, 26));
        fondClavier.add(jButton0);

        jButtonDiese.setText("#");
        jButtonDiese.setToolTipText("Appuyer");
        jButtonDiese.setPreferredSize(new java.awt.Dimension(26, 26));
        jButtonDiese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDieseMouseClicked(evt);
            }
        });
        fondClavier.add(jButtonDiese);

        getContentPane().add(fondClavier);
        fondClavier.setBounds(10, 70, 190, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButtonDieseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDieseMouseClicked
        // TODO add your handling code here:
        textMess.setText("");
        textMess.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jButtonDieseMouseClicked

    private void jButtonEtoileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEtoileMouseClicked
        // TODO add your handling code here:
        if (textMess.getText().equals("1234")) {
            textMess.setText("Code bon");
            textMess.setBackground(Color.GREEN);
            compteurErreur = 0;
        } else {
            textMess.setText("Code faux");
            textMess.setBackground(Color.RED);
            compteurErreur++;
            if (compteurErreur >= 3) {
                textMess.setText("Clavier bloqué");
            }
        }
    }//GEN-LAST:event_jButtonEtoileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenClavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenClavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenClavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenClavier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenClavier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondClavier;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDiese;
    private javax.swing.JButton jButtonEtoile;
    private javax.swing.JTextField textMess;
    // End of variables declaration//GEN-END:variables

    public class GestionnaireTouche implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            //récupération de l'objet à l'origine de l'événement
            Object src = e.getSource();
            //si l'objet est un bouton
            if (src instanceof JButton) {
                if (textMess.getText().length() < 4) {
                    //récupérer le texte du bouton
                    String texteDeLaTouche = ((JButton) src).getText();
                    //ajouter le texte du bouton au texte déjà présent dans la zone de texte
                    textMess.setText(textMess.getText() + texteDeLaTouche);
                }
            }
        }
    }
}
